### ISSUE TITLE
card-stock selectCard function should check if the card is actually selectable

### ISSUE THREAD

**Issue by jordijansen** [thoun/bga-cards#1]
Hi,

I've run into some weird behavior I did not expect, I've activated 'multiple' selectionMode on a CardStock and the cards get the class .selectable. When I use the setSelectableCards to disable a few cards for selection they get the class .disabled and lose the .selectable class as expected.

However when I now click on one of those .disabled cards it is still added to the selection.

Would it be good to add a check to the selectCard function if the card actually has the .selectable class?

For example:
```
public selectCard(card: T, silent: boolean = false) {
        const element = this.getCardElement(card);

        if (this.selectionMode == 'none') {
            return;
        }
      
        if (!element.classList.contains('selectable')) {
            return;
        }
        
        if (this.selectionMode === 'single') {
            this.cards.filter(c => this.manager.getId(c) != this.manager.getId(card)).forEach(c => this.unselectCard(c, true));
        }

        element.classList.add('selected');
        this.selectedCards.push(card);
        
        if (!silent) {
            this.onSelectionChange?.(this.selectedCards.slice(), card);
        }
    }
```

**Comment by thoun** [comment]
Yeah that make sense !

**Comment by jordijansen** [comment]
Great I'll see if I can make an MR for it!

**Comment by thoun** [comment]
I  took inspiration from your PR but completed it and made a demo.
https://github.com/thoun/bga-cards/releases/tag/1.1.0

**Comment by thoun** [comment]
If you don't want to change your classes definition, add this to you manager settings : 
            selectableCardClass: 'selectable',
            unselectableCardClass: 'disabled',
            selectedCardClass: 'selected',
So it will be compatible with old classes names.
